options  (direct=true, bindsize=999999999, rows=100000000)
load data
  CHARACTERSET WE8ISO8859P1
  append into table GFAS_ACCOUNTEXTNALREFERENCETBL 
  fields terminated by "~"
(
 PRODUCTGROUP                   "TRIM(:PRODUCTGROUP)"
,GFASACCOUNT                   	"TRIM(:GFASACCOUNT)"
,EXTERNALREFERENCETYPECODE      "TRIM(:EXTERNALREFERENCETYPECODE)"
,ACCOUNTEXTERNALREFERENCE       "TRIM(:ACCOUNTEXTERNALREFERENCE)"
,CREATEDBYUSERID                "TRIM(:CREATEDBYUSERID)"
,CREATEDDATE                   	"TRIM(:CREATEDDATE)"
,LASTUPDATEDBYUSERID            "TRIM(:LASTUPDATEDBYUSERID)"
,LASTUPDATEDDATE                "TRIM(:LASTUPDATEDDATE)"
,RECORDNUMBER                   TERMINATED BY WHITESPACE
)
