#!/usr/bin/env bash
echo "start Initialize_Environment_Parameters"
source "$RUNENV".config
start_time="$(date -u +%s.%N)"
export login_STAGE="$P_login_STAGE"
export login_LOB="$P_login_LOB"
export login_SMS="$P_login_SMS"
export login_SP="$P_login_SP"
export login_ROA="$P_login_ROA"
export repopath="$P_repopath"
export Phyloc="$P_Phyloc"
export PMigRUNFILES="$P_Mig_RUN_FILES"
export DedupeValue="$P_DedupeValue"
export Spoolfolder="$p_Spoolfolder"
export tableparallel="$P_tableparallel"
#Below doesnt require changes as they are relative to repo
export migspoolloc="$repopath"
export loc=""$Phyloc"/"$PMigRUNFILES""
export statsloc=""$loc"/DMP_STATS"
export spoolloc=""$loc"/"$Spoolfolder""
export fxtblloc=""$repopath"/BackEnd/Transformation_Mig_Scripts/Transformation_Environment/DDL_SCRIPTS"
export dmtblloc=""$repopath"/BackEnd/Environment/Execution"
export pretrnsf_loc=""$repopath"/BackEnd/Pre_TransformationCheck"
export trnsf_loc=""$repopath"/BackEnd/Transformation"
export premig_loc=""$repopath"/BackEnd/Pre_Migration"
export mig_loc=""$repopath"/BackEnd/Migration"
export misc_loc=""$repopath"/BackEnd/BackendScripts"
export constraints_loc=""$repopath"/BackEnd/Environment/Misc"
export g1g2_loc=""$repopath"/BackEnd/Mig_G1G2_Scripts"
export syndeploy=""$repopath"/Spool/SYN_Deploy"
export ControlLoc=""$repopath"/Sqlldr/Control_Files"
export dedupe_loc=""$repopath"/BackEnd/Dedupe_Scripts"
export dayzero_loc=""$repopath"/BackEnd/DayZero"
export cdscloc=""$Phyloc"/MINT_FILES/MINT_HIST"
export ext=".log"

echo "===============<><><><><><><><><><><><><><><><><><><><><><><><><><><>===================="
echo "spoolloc="$spoolloc""
echo "login_STAGE="$login_STAGE""
echo "login_LOB="$login_LOB""
echo "login_SP="$login_SP""
echo "login_SMS="$login_SMS""
echo "login_ROA="$login_ROA""
echo "Phyloc="$Phyloc""
echo "PMigRUNFILES="$PMigRUNFILES""
echo "loc="$loc""
echo "migspoolloc="$migspoolloc""
echo "fxtblloc="$fxtblloc""
echo "statsloc="$statsloc""
echo "dmtblloc="$dmtblloc""
echo "syndeploy="$syndeploy""
echo "pretrnsf_loc="$pretrnsf_loc""
echo "trnsf_loc="$trnsf_loc""
echo "premig_loc="$premig_loc""
echo "mig_loc="$mig_loc""
echo "misc_loc="$misc_loc""
echo "constraints_loc="$constraints_loc""
echo "g1g2_loc="$g1g2_loc""
echo "dedupe_loc="$dedupe_loc""
echo "dayzero_loc="$dayzero_loc""
echo "cdscloc="$cdscloc""
echo "ext="$ext""
echo "DedupeValue="$DedupeValue""
echo "Spoolfolder="$Spoolfolder""
echo "tableparallel="$tableparallel""
if [ -z "$tableparallel" ]
then
     echo "\$tableparallel tableparallel is empty and Table will remain parallel"
else
     echo "\$tableparallel tableparallel is non empty"
	if [ $tableparallel == "N" ]
	then
		echo " Tables will now be made non parallel"
	else 
		echo "tableparallel is $tableparallel   and Tables will remain parallel"
	fi
fi
echo "===============<><><><><><><><><><><><><><><><><><><><><><><><><><><>===================="
logtime="$(date -u +%d%h%y_%T)"
echo "Started execution at:::"$(date)"::logtime::"$logtime"" |& tee -a "$spoolloc"/"$RUNENV"_Initialize_Environment_Parameters_"$logtime""$ext"
prog_start_time="$(date -u +%s.%N)"
wait
end_time="$(date -u +%s.%N)"
elapsed="$(bc <<<"$end_time-$start_time")"
echo " Total of $elapsed seconds elapsed for process" |& tee -a "$spoolloc"/"$RUNENV"_Initialize_Environment_Parameters_"$logtime""$ext"
echo "Ended Execution at:::"$(date)"" |& tee -a "$spoolloc"/"$RUNENV"_Initialize_Environment_Parameters_"$logtime""$ext"

#nohup bash /gtaplocal/GTAP_MDR_INFILES/Initialize_Environment_Parameters.sh &